export const referredByOptions = [
  "Choose",
  "Syed Danish Ali",
  "Taskeen Tarannum",
  "Farha Khan",
  "Arzoo Siraj",
  "Gulfisha khan",
  "Heena",
  "Nasreen Banu",
  "Zeba Fatima",
  "Mufti Sajjad Hussain Qasmi",
  "Saba Manzoor",
  "Tasneem Khan",
  "Saara Shaikh",
  "Mubashira Yusuf",
  "Sana Manzoor",
  "Nousheen Tarannum",
  "Nurjahan Akhtar",
  "Niloufer Baig",
  "Siyasat Advertisement",
  "Website",
  "Facebook",
  "Linkedin",
  "Instagram",
  "Youtube",
  "Through WhatsApp Group Reference",
  "Aleena Beg",
  "Ayesha Afsana",
  "Shama Swaliha",
  "Syed Ammar",
  "Akram Khan",
  "Mf Ahmadullah Qasemi",
  "Sadiya Ashraf",
  "Nazish Massud",
  "Abdul Majid"
];
